name       : easytag
version    : 2.4.0
release    : 1
source     :
    - https://download.gnome.org/sources/easytag/2.4/easytag-2.4.0.tar.xz : b8d882bc168abca96b1b369b10e5b97fa29a7a43f7b33f34489768d111610c3d
license    : GPL-2.0
summary    : EasyTAG is a simple application for viewing and editing tags in audio files.
description: |
    EasyTAG is a simple application for viewing and editing tags in audio files.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(gnome-doc-utils)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(ogg)
    - pkgconfig(opus)
    - pkgconfig(taglib)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - appdata-tools
    - intltool
    - libid3tag-devel
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
