name       : easytag
version    : 2.4.2
release    : 9
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/easytag/2.4/easytag-2.4.2.tar.xz : 148129cc948c05b0560aeb60fb06260b8550f252a88eb439d8c7fee7ec10d2e6
license    : GPL-2.0
component  : multimedia.audio
summary    : EasyTAG is a simple application for viewing and editing tags in audio
    files.
description: |
    EasyTAG is a simple application for viewing and editing tags in audio files.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(glib-2.0)
    - pkgconfig(gnome-doc-utils)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(id3tag)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(ogg)
    - pkgconfig(opus)
    - pkgconfig(opusfile)
    - pkgconfig(speex)
    - pkgconfig(taglib)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - appdata-tools
    - id3lib-devel
    - itstool
    - lame-devel
    - libmad-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    sed -i "s:inode/directory;::" $installdir/usr/share/applications/easytag.desktop
