name       : easytag
version    : 2.4.3
release    : 16
source     :
    - https://download.gnome.org/sources/easytag/2.4/easytag-2.4.3.tar.xz : fc51ee92a705e3c5979dff1655f7496effb68b98f1ada0547e8cbbc033b67dd5
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Audio file metadata editor
description: |
    EasyTAG is a simple application for viewing and editing tags in audio files.
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(flac)
    - pkgconfig(gnome-doc-utils)
    - pkgconfig(id3tag)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(mad)
    - pkgconfig(opusfile)
    - pkgconfig(speex)
    - pkgconfig(taglib)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - id3lib-devel
    - itstool
    - lame-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    sed -i "s:inode/directory;::" $installdir/usr/share/applications/easytag.desktop
